server:
  port: 2333
  address: 127.0.0.1
lavalink:
  server:
    password: "password"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
    bufferDurationMs: 4000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics